# Generated by Django 5.1.3 on 2024-11-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status_type",
            field=models.CharField(
                choices=[("1", "PENDING"), ("2", "COMPLETED")], default=1, max_length=2
            ),
        ),
    ]
